In [24]:
import torch
import math

In [4]:
d_model = 8

In [5]:
even_i = torch.arange(0, d_model , 2).float()
even_i

tensor([0., 2., 4., 6.])

In [6]:
even_denom = torch.pow(10000, even_i/d_model)
even_denom

tensor([   1.,   10.,  100., 1000.])

In [9]:
odd_i = torch.arange(1, d_model , 2).float()
odd_denom = torch.pow(10000 , (odd_i-1)/d_model)

In [10]:
odd_denom

tensor([   1.,   10.,  100., 1000.])

In [11]:
denom = even_denom

In [12]:
max_seq_len = 10
position = torch.arange(max_seq_len , dtype = torch.float).reshape(max_seq_len , 1)
position

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [13]:
even_PE = torch.sin(position / denom)
odd_PE = torch.cos(position/denom)

In [14]:
even_PE

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.8415,  0.0998,  0.0100,  0.0010],
        [ 0.9093,  0.1987,  0.0200,  0.0020],
        [ 0.1411,  0.2955,  0.0300,  0.0030],
        [-0.7568,  0.3894,  0.0400,  0.0040],
        [-0.9589,  0.4794,  0.0500,  0.0050],
        [-0.2794,  0.5646,  0.0600,  0.0060],
        [ 0.6570,  0.6442,  0.0699,  0.0070],
        [ 0.9894,  0.7174,  0.0799,  0.0080],
        [ 0.4121,  0.7833,  0.0899,  0.0090]])

In [15]:
stacked = torch.stack([even_PE , odd_PE] , dim= 2)

In [18]:
PE = torch.flatten(stacked ,start_dim = 1, end_dim = 2)

In [19]:
PE

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
          9.9995e-01,  1.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
          9.9920e-01,  4.0000e-03,  9.9999e-01],
        [-9.5892e-01,  2.8366e-01,  4.7943e-01,  8.7758e-01,  4.9979e-02,
          9.9875e-01,  5.0000e-03,  9.9999e-01],
        [-2.7942e-01,  9.6017e-01,  5.6464e-01,  8.2534e-01,  5.9964e-02,
          9.9820e-01,  6.0000e-03,  9.9998e-01],
        [ 6.5699e-01,  7.5390e-01,  6.4422e-01,  7.6484e-01,  6.9943e-02,
          9.9755e-01,  6.9999e-03,  9.9998e-01],
        [ 9.8936

In [23]:
torch.arange(0 , 15).unsqueeze(1).shape

torch.Size([15, 1])

In [25]:
torch.exp(torch.arange(0, 20, 2).float()*(-math.log(10000.0)/20))

tensor([1.0000e+00, 3.9811e-01, 1.5849e-01, 6.3096e-02, 2.5119e-02, 1.0000e-02,
        3.9811e-03, 1.5849e-03, 6.3096e-04, 2.5119e-04])

In [29]:
d_model = 20
div_log = torch.exp(torch.arange(0, d_model, 2).float()*(-math.log(10000.0)/d_model))
div_pow = torch.pow(10000 , torch.arange(0 , d_model , 2).float()/d_model)

In [30]:
div_log

tensor([1.0000e+00, 3.9811e-01, 1.5849e-01, 6.3096e-02, 2.5119e-02, 1.0000e-02,
        3.9811e-03, 1.5849e-03, 6.3096e-04, 2.5119e-04])

In [31]:
div_pow

tensor([1.0000e+00, 2.5119e+00, 6.3096e+00, 1.5849e+01, 3.9811e+01, 1.0000e+02,
        2.5119e+02, 6.3096e+02, 1.5849e+03, 3.9811e+03])

In [32]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

In [33]:
sequence_len = 4
batch_size = 1
input_dim = 512
d_model = 512
x = torch.randn((batch_size , sequence_len , input_dim))

In [34]:
x.shape

torch.Size([1, 4, 512])

In [46]:
qkv_layer = nn.Linear(input_dim , 3*d_model)
qkv = qkv_layer(x)

In [47]:
qkv.shape

torch.Size([1, 4, 1536])

In [49]:
num_heads =8
head_dims = d_model//num_heads
qkv = qkv.reshape(batch_size , sequence_len , num_heads , 3*head_dims)
qkv = qkv.permute(0,2,1,3)
qkv.shape

torch.Size([1, 8, 4, 192])

In [50]:
q, k , v = qkv.chunk(3, dim =-1)
q.shape , k.shape , v.shape

(torch.Size([1, 8, 4, 64]),
 torch.Size([1, 8, 4, 64]),
 torch.Size([1, 8, 4, 64]))

In [51]:
d_k = q.size()[-1]
scaled = torch.matmul(q , k.transpose(-2,-1))/math.sqrt(d_k)
scaled.shape

torch.Size([1, 8, 4, 4])

In [52]:
#masking
mask = torch.full(scaled.size() , float('-inf'))
mask = torch.triu(mask , diagonal = 1)
mask[0][1]

tensor([[0., -inf, -inf, -inf],
        [0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])

In [55]:
(scaled+mask)[0][0]

tensor([[ 0.6306,    -inf,    -inf,    -inf],
        [-0.2864,  0.3027,    -inf,    -inf],
        [-0.3335,  0.0101, -0.0480,    -inf],
        [-0.1058, -0.4538, -0.0608,  0.1491]], grad_fn=<SelectBackward0>)

In [56]:
(scaled+mask).shape

torch.Size([1, 8, 4, 4])

In [57]:
scaled += mask

In [58]:
attention = F.softmax(scaled , dim = -1)
attention.shape

torch.Size([1, 8, 4, 4])

In [59]:
values = torch.matmul(attention , v)
values.shape

torch.Size([1, 8, 4, 64])

In [ ]:
import math

def scaled_dot_product(q , k, v , mask = None):
    d_k = q.size()[-1]
    scaled = torch.matmul(q , k.transpose(-1,-2))/math.sqrt(d_k)
    if mask is not None :
        scaled += mask
    attention = F.softmax(scaled , dim = -1)
    values = torch.matmul(attention , v)
    return values , attention
    

In [ ]:
values , attention = scaled_dot_product(q, k, v, mask=None)


In [60]:
values.size()

torch.Size([1, 8, 4, 64])

In [62]:
values = values.reshape(batch_size , sequence_len , num_heads*head_dim)
values.size()

NameError: name 'head_dim' is not defined

In [ ]:
linear_layer = nn.Linear(d_model , d_model)
out= linear_layer(values)
out.shape

In [63]:
import torch
import torch.nn as nn
import math

def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size()[-1]
    scaled = torch.matmul(q, k.transpose(-1, -2)) / math.sqrt(d_k)
    if mask is not None:
        scaled += mask
    attention = F.softmax(scaled, dim=-1)
    values = torch.matmul(attention, v)
    return values, attention

class MultiheadAttention(nn.Module):

    def __init__(self, input_dim, d_model, num_heads):
        super().__init__()
        self.input_dim = input_dim
        self.d_model = d_model
        self.num_heads = num_heads
        self.head_dim = d_model // num_heads
        self.qkv_layer = nn.Linear(input_dim , 3 * d_model)
        self.linear_layer = nn.Linear(d_model, d_model)
    
    def forward(self, x, mask=None):
        batch_size, sequence_length, input_dim = x.size()
        qkv = self.qkv_layer(x)
        qkv = qkv.reshape(batch_size, sequence_length, self.num_heads, 3 * self.head_dim)
        qkv = qkv.permute(0, 2, 1, 3)
        q, k, v = qkv.chunk(3, dim=-1)
        values, attention = scaled_dot_product(q, k, v, mask)
        values = values.reshape(batch_size, sequence_length, self.num_heads * self.head_dim)
        out = self.linear_layer(values)
        return out

In [64]:
input_dim = 1024 
d_model = 512
num_heads = 80

batch_size = 30
seq_len = 5
x = torch.randn( (batch_size, sequence_length, input_dim) )

model = MultiheadAttention(input_dim, d_model, num_heads)
out = model.forward(x)

x.size(): torch.Size([30, 5, 1024])
qkv.size(): torch.Size([30, 5, 1536])
qkv.size(): torch.Size([30, 5, 8, 192])
qkv.size(): torch.Size([30, 8, 5, 192])
q size: torch.Size([30, 8, 5, 64]), k size: torch.Size([30, 8, 5, 64]), v size: torch.Size([30, 8, 5, 64]), 
values.size(): torch.Size([30, 8, 5, 64]), attention.size:torch.Size([30, 8, 5, 5]) 
values.size(): torch.Size([30, 5, 512])
out.size(): torch.Size([30, 5, 512])


In [ ]:
input_dim = 1024
seq_len = 7
batch_size = 16
d_model = 512

x = torch.randn((batch_size ,seq_len , input_dim ))

In [ ]:
x = torch.randn((1,12,15 , 128))

In [65]:
1024/8

128.0

In [ ]:
inp =(7, 19 , 1024)
Qw = (512 , 512) # learn
Kw = (512 , 512) # learn 
Vw = (512 , 512) # learn

q , k , v = inp.copy()

numHead = 8
#reshape to (bs , seq len , head , d-model/head)
inpShape = (7 , 19 , 8 , 128)  # torch,permute(-1 , -2)
reshaped_inp = (7,8 , 19 , 128)

scaled = matmul(k , Tranpose(q)) /sprt(1024/ 8)
attention  = softmax(scaled) # size = (7,8, 19 , 19)

value = torch.matmul(attention, v) # size (7 , 8,19 , 128)
value.transpose(1,2).contiguous().view(b , s , 1024)